pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/prakash411/OnlineRentSystem.git'
            }
        }
    }

    stage('Check dotnet') {
        steps {
            sh '''
                whoami
                which dotnet
                dotnet --info
                openssl version || true
                ldconfig -p | grep -E 'libssl|libcrypto' || true
            '''
        }
    }

    stage('Restore') {
        steps {
            sh 'dotnet restore renter/renter.csproj'
        }
    }

    stage('Build') {
        steps {
            sh 'dotnet build renter/renter.csproj -c Release --no-restore'
        }
    }

    stage('Publish') {
        steps {
            sh 'dotnet publish renter/renter.csproj -c Release -o publish --no-build'
        }
    }

}
